# This file was generated by GoReleaser. DO NOT EDIT.
class Lile < Formula
  desc ""
  homepage ""
  version "2.2.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lileio/lile/releases/download/v2.2.12/lile_2.2.12_Darwin_x86_64.tar.gz"
    sha256 "c71c99afec11f7f0e5797953d26cfe5894d1ce3c0d4a1e4b9432fd4c86bfb45d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lileio/lile/releases/download/v2.2.12/lile_2.2.12_Linux_x86_64.tar.gz"
      sha256 "ae4f54d2d8654f5cfc1771145985f2d167d7e053b7c6b66eaa241e67a9eb94c7"
    end
  end

  def install
    bin.install "lile"
    bin.install "protoc-gen-lile-server"
  end
end
