# This file was generated by GoReleaser. DO NOT EDIT.
class Lile < Formula
  desc ""
  homepage ""
  version "2.2.13"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lileio/lile/releases/download/v2.2.13/lile_2.2.13_Darwin_x86_64.tar.gz"
    sha256 "b81e88d6935c07d6832e59768072320ea8ebbf75cde8baef6f9f8a5d82252642"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lileio/lile/releases/download/v2.2.13/lile_2.2.13_Linux_x86_64.tar.gz"
      sha256 "eb109975833b55a7e7495df277db02009f5b77f054c2c9c3d5e6491d4ff75c03"
    end
  end

  def install
    bin.install "lile"
    bin.install "protoc-gen-lile-server"
  end
end
