# This file was generated by GoReleaser. DO NOT EDIT.
class Lile < Formula
  desc ""
  homepage ""
  url "https://github.com/lileio/lile/releases/download/v2.2.0-next/lile_2.2.0-next_Darwin_x86_64.tar.gz"
  version "2.2.0-next"
  sha256 "2c7b1cad7d6275a1153491841a566b35067223d1c18f18f68e627764fe39fa5d"

  def install
    bin.install "lile"
  end
end
